display:
  default:
    display_title: Noklusējuma
    display_options:
      exposed_form:
        options:
          submit_button: Apstiprināt
          reset_button_label: Attīrīt
          exposed_sorts_label: 'Kārtot pēc'
          sort_desc_label: Dilst.
