label: Saturs
display:
  default:
    display_title: Noklusējuma
    display_options:
      title: Saturs
      fields:
        title:
          label: Nosaukums
        type:
          label: 'Satura veids'
          separator: ', '
        name:
          label: Autors
        status:
          label: Statuss
          settings:
            format_custom_true: Publicēts
        changed:
          label: Atjaunināts
        langcode:
          label: Valoda
          separator: ', '
        operations:
          label: Darbības
      pager:
        options:
          tags:
            next: 'Nākamais ›'
            previous: '‹ Iepriekšējais'
      exposed_form:
        options:
          submit_button: Filtrēt
          reset_button_label: Attīrīt
          exposed_sorts_label: 'Kārtot pēc'
          sort_desc_label: Dilst.
      filters:
        title:
          expose:
            label: Nosaukums
        type:
          expose:
            label: 'Satura veids'
        status:
          expose:
            label: Statuss
          group_info:
            group_items:
              1:
                title: Publicēts
        langcode:
          expose:
            label: Valoda
  page_1:
    display_title: Lapa
    display_options:
      menu:
        title: Saturs
      tab_options:
        title: Saturs
