label: Multivide
display:
  default:
    display_title: Noklusējuma
    display_options:
      title: Multivide
      fields:
        uid:
          label: Autors
        operations:
          label: Darbības
      pager:
        options:
          tags:
            next: 'Nākamais ›'
            previous: '‹ Iepriekšējais'
      exposed_form:
        options:
          reset_button_label: Attīrīt
      filters:
        langcode:
          expose:
            label: Valoda
  media_page_list:
    display_title: Multivide
    display_options:
      menu:
        title: Multivide
