display:
  default:
    display_title: Noklusējuma
    display_options:
      fields:
        link:
          label: Darbības
      exposed_form:
        options:
          reset_button_label: Attīrīt
