label: Faili
display:
  default:
    display_title: Noklusējuma
    display_options:
      title: Faili
      fields:
        filename:
          label: Nosaukums
          separator: ', '
        filemime:
          label: 'MIME tips'
        filesize:
          label: Izmērs
        status:
          label: Statuss
        changed:
          label: 'Izmaiņu datums'
        operations:
          label: Darbības
      pager:
        options:
          tags:
            next: 'Nākamais ›'
            previous: '‹ Iepriekšējais'
          expose:
            items_per_page_label: 'Vienumi vienā lapā'
            items_per_page_options_all_label: '- Visi -'
            offset_label: Atkāpe
      exposed_form:
        options:
          submit_button: Filtrēt
          reset_button_label: Attīrīt
          exposed_sorts_label: 'Kārtot pēc'
          sort_desc_label: Dilst.
      filters:
        filename:
          expose:
            label: 'Faila nosaukums'
        filemime:
          expose:
            label: 'MIME tips'
        status:
          expose:
            label: Statuss
  page_1:
    display_options:
      menu:
        title: Faili
  page_2:
    display_options:
      fields:
        type:
          label: 'Entītijas veids'
      pager:
        options:
          tags:
            next: 'Nākamais ›'
            previous: '‹ Iepriekšējais'
          expose:
            items_per_page_label: 'Vienumi vienā lapā'
            items_per_page_options_all_label: '- Visi -'
            offset_label: Atkāpe
      arguments:
        fid:
          exception:
            title: Visi
