display:
  default:
    display_title: Noklusējuma
    display_options:
      fields:
        title:
          label: Nosaukums
        type:
          label: 'Satura veids'
        name:
          label: Autors
        langcode:
          label: Valoda
        operations:
          label: Darbības
      pager:
        options:
          tags:
            next: 'Nākamais ›'
            previous: '‹ Iepriekšējais'
      exposed_form:
        options:
          reset_button_label: Attīrīt
      filters:
        title:
          expose:
            label: Nosaukums
        type:
          expose:
            label: 'Satura veids'
        langcode:
          expose:
            label: Valoda
