_core:
  default_config_hash: Cc_tyfGTKws_Eh02fkcPOInps8qngAKJqdMAAsOEUcA
phone: '+07 554 332 32223232'
email: contact@example.com
location: '37 San Fairport, NY 14450'
facebook_url: 'http://psmhydraulics.local/admin/config/system/psm-site'
instagram_url: ''
linkedin_url: ''
x_url: ''
