_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en-gb
uuid: 75412278-4710-418e-aadc-7782bee3a250
name: 'PSM Hydraulics'
mail: ritvars.resnis@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en-gb
mail_notification: null
